import sys
import traceback

from PyQt4.QtGui import *
from PyQt4.QtCore import *

from Ui_submitter import Ui_MainWindow #generated by Qt UI Designer

from LoggingSetup import logger #Logging is a library for creating log files. LoggingSetup is a script that sets up a logger

from JobTicket import MayaTicket

class SubmitterWindow( QMainWindow, Ui_MainWindow ):

    def __init__( self ):
        """Initializes the Maya render job submission window."""

        QMainWindow.__init__( self )
        self.setupUi( self ) #self, self

        QObject.connect(self.submitButton, SIGNAL("clicked()"), self.doSubmit)

        sys.argv.extend (['1', '1', '1'])
        scene, start, end, by = sys.argv[1:5] # proper command line args would be nice
        scene = scene.replace ('\\', '/')
        self.sceneLabel.setText( scene )
        if 'scenes' not in scene.split ('/'):
            self.errorLabel.setText ('<B>File not in a scene folder.</B>')
            self.submitButton.setEnabled (False)
        if ':' in scene:
            self.errorLabel.setText ('<B>Use UNC paths, not mapped drives.</B>')
            self.submitButton.setEnabled (False)

        self.startSpinBox.setValue( eval (start ) )
        self.endSpinBox.setValue( eval( end ) )

# called by pressing the "submit" button in the Qt main window
    def doSubmit( self ):
        """Submits a job ticket for this scene to be split into tasks and processed."""

        logger.debug ('doSubmit')

        sceneFile = str( self.sceneLabel.text( ) )
        startFrame = self.startSpinBox.value( )
        endFrame = self.endSpinBox.value( )
        batchSize = self.batchSizeSpinBox.value( )
        priority = self.prioritySpinBox.value( )
        if 'scenes' in sceneFile.split ('/'):
            MayaTicket( sceneFile, startFrame, endFrame, batchSize, priority ).submit( )
            self.errorLabel.setText ('Done. Close the window.')


if __name__ == '__main__':
    try:
        logger.debug(sys.argv) # prints out argv
        app = QApplication( sys.argv ) # argv should be theoretically empty

        window = SubmitterWindow( )

        window.show( )
        retcode = app.exec_( )
        sys.exit( retcode )
    except Exception, e:
        logger.error( traceback.format_exc( e ) )
        raise


